### ISSUE TITLE
Detecting the custom tab close event

### ISSUE THREAD

**Issue by aeirola** [droibit/react-native-custom-tabs#16]
Would be nice to be able to determine when the custom tab is closed, so that the application would be able to update itself to possible actions taken within the chrome tab. So would be nice if one could pass an callback argument, or register an eventlistener for when the user closes the custom tab.

Not sure if there already are some nice ways of tracking the foreground activity in react native on Android. If there are, then that would of course also be ok.

For reference `react-native-safari-view` has an [`onDismiss`](https://github.com/naoufal/react-native-safari-view#ondismiss) event

**Comment by ataillefer** [comment]
Hi,

We're indeed using react-native's [AppState](https://facebook.github.io/react-native/docs/appstate.html) to track the foreground activity and detect when the Chrome custom tab is closed:

```
import React, { Component } from 'react';
import { AppState } from 'react-native';

class MyComponent extends Component {

  componentDidMount() {
    AppState.addEventListener('change', this._handleAppStateChange);
  }

  componentWillUnmount() {
    AppState.removeEventListener('change', this._handleAppStateChange);
  }

  _handleAppStateChange(nextAppState) {
    if (nextAppState === 'active') {
      // update app
    }
  }
}
```

This works great, hope it helps!

**Comment by aeirola** [comment]
Oh, cool. Thanks @ataillefer! This solves my issue.

**Comment by fiznool** [comment]
Unfortunately this doesn't exactly mimic the behaviour as seen in `react-native-safari-view`, as the AppState monitor also fires when the app comes back into the foreground after the home screen was displayed, a phone call ended, etc.

It would be nice if we could just be notified when the Chrome custom tab is shown/hidden.
