### ISSUE TITLE
Undefined is not an object (evaluating 'CustomTabsManager.openURL')

### ISSUE THREAD

**Issue by KeizerDev** [droibit/react-native-custom-tabs#3]
When just copying your example and rebuilding the app, I get this message when I try fire up a new tab:
`Undefined is not an object (evaluating 'CustomTabsManager.openURL')`

**Comment by droibit** [comment]
@KeizerDev   
Sorry for the late reply.
This error occurs if `CustomTabsPackage` is not provided. I updated the installation of README.md.

* https://github.com/droibit/react-native-custom-tabs#android

**Comment by ethanyuwang** [comment]
@droibit 
I imported `CustomTabsPackage` but still have the same error

My `MainApplication.java`: 

```
import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import com.dstaley.ReactNativeChromeCustomTabs.ChromeCustomTabsPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "Glever";
    }

	/**
	* A list of packages used by the app. If the app uses additional views
	* or modules besides the default ones, add more packages here.
	*/
	@Override
    protected List<ReactPackage> getPackages() {
		return Arrays.<ReactPackage>asList(
			new MainReactPackage(),
			new ChromeCustomTabsPackage(this)  // <-- Register
		);
	}


}
```

**Comment by ataillefer** [comment]
I guess @ethanyuwang 's issue is in the Javascript code.

You need to import the `CustomTabs` object from the `react-native-custom-tabs` library at the top of your file then use it with`CustomTabs.openURL(...)`:
```
import { CustomTabs } from 'react-native-custom-tabs';

...

CustomTabs.openURL('someURL')
    .catch((e) => handleError(e));
```

**Comment by taslimy** [comment]
Hi i'm having this issue as well! i am using expo also or is this not compatible?
