### ISSUE TITLE
Path or configuration is wrong when compiling project to ios

### ISSUE THREAD

**Issue by vincent-cm** [droibit/react-native-custom-tabs#59]
react-native-custom-tabs/ios/ReactNativeCustomTabs/DBChromeManager.m:12:
../../react-native/React/Base/RCTUtils.h:14:9: fatal error: 'React/RCTAssert.h' file not found
#import <React/RCTAssert.h>
        ^~~~~~~~~~~~~~~~~~~
1 error generated.

My config

System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 578.36 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    npm: 6.13.2 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12.0 => 16.12.0
    react-native: 0.61.5 => 0.61.5

**Comment by San10694** [comment]
How did you solve it @vincent-cm ? I am getting the same issue in react-native 0.61.5

**Comment by csouth3** [comment]
Having the same issue as well.
