### ISSUE TITLE
Already have maven{}

### ISSUE THREAD

**Issue by andyscraven** [droibit/react-native-custom-tabs#9]
I already have:

        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }

In my build.gradle.  Do I replace it or have both as per your setup?

**Comment by droibit** [comment]
Please add `maven { url "https://jitpack.io" }` like example app.

- https://github.com/droibit/react-native-custom-tabs/blob/develop/example/android/build.gradle#L19-L23
